name: Brendan Ryan

exclude: ["_dev", "Gemfile", "Gemfile.lock", "_compress_images_cache.yml"]

plugins:
  - jekyll-compress-images
  - jekyll-redirect-from

imageoptim:
  svgo: false

destination: ./build
